apiVersion: apps/v1
kind: Deployment
metadata:
  name: runners-app
  namespace: runners-space
spec:
  selector:
    matchLabels:
      app: runners-app
  replicas: 1
  template:
    metadata:
      labels:
        app: runners-app
    spec:
      containers:
       - name: runners-app
         image: runners-app:latest
         imagePullPolicy: Never
         ports:
          - containerPort: 8080
         env:
         - name: ENV
           value: "k8s"   
