apiVersion: v1
kind: Service
metadata:
  name: runners-app-service
  namespace: runners-space
spec:
  selector:
    app: runners-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
